# Generated by Django 2.0.9 on 2018-10-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='signup',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(db_index=True, default=None, max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
