# Generated by Django 2.0.9 on 2018-10-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20181025_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='signup',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
