# Generated by Django 2.0.9 on 2018-10-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20181025_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phoneNumber',
        ),
    ]
