# Generated by Django 2.0.9 on 2018-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181030_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
