# Generated by Django 2.0.9 on 2018-11-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181101_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='status',
        ),
    ]
