# Generated by Django 2.1.2 on 2018-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/default.png', null=True, upload_to='static/img'),
        ),
    ]
