# Generated by Django 2.0.9 on 2018-11-06 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('twtid', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='twtid', to='accounts.Tweets')),
            ],
        ),
    ]
