# Generated by Django 2.1.2 on 2018-11-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20181108_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='accounts.Tweets'),
        ),
    ]
