# Generated by Django 2.1.2 on 2018-11-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20181109_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like_id',
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
