# Generated by Django 2.0.9 on 2018-10-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='number',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default=None, max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='phonenumber',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
