# Generated by Django 2.0.9 on 2018-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20181012_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
