# Generated by Django 2.0.9 on 2018-10-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('phonenumber', models.CharField(default=None, max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, default=None, max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default=None, max_length=20, unique=True)),
            ],
        ),
    ]
