# Generated by Django 2.0.9 on 2018-10-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Signup'),
        ),
    ]
