# Generated by Django 2.0.9 on 2018-10-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20181016_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phonenumber',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
